In [1]:
import matplotlib.pyplot as plt
from os.path import isfile, join, abspath, dirname
from os import listdir
import sys
import pandas as pd
import numpy as np

In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [3]:
sys.path.insert(0, '../src/')

In [4]:
SAVE=False

In [5]:
from logger import LogData, TemporalLogger, EnvLogger
from utils import plot_typography

In [6]:
plot_typography(True, 12, 14, 16)

In [7]:
__file__ = "analysis.ipynb"
log_dir = join(dirname(dirname(abspath(__file__))), "log")
decimate = 100


def figure_factory(log_dir, env, variant, rew_scale=5, feat_scale=1, decimate=100, save=True, loc_feat=1, loc_rwd=4, zoom_feat=2.5, zoom_rwd=2.5):
    # sanity check
    if variant not in [0,4]:
        raise ValueError(f"Invalid variant, got {variant}, should be 0 or 4")
    
    # load data 
    el = EnvLogger(f"{env}NoFrameskip-v{variant}", log_dir, decimate)

    # plot
    rwd_metrics = el.plot_decorator(keyword="rewards", save=save, y_inset_std_scale=rew_scale, loc=loc_rwd, zoom=zoom_rwd)
    el.plot_decorator(keyword="features", save=save, y_inset_std_scale=feat_scale, loc=loc_feat, zoom=zoom_feat)

    return rwd_metrics

In [ ]:
pong_metrics4 = figure_factory(log_dir, "Pong", 4, 5, .5, 100, save=SAVE, loc_rwd=4, loc_feat=1, zoom_rwd=2., zoom_feat=4) 

In [ ]:
breakout_metrics4 = figure_factory(log_dir, "Breakout", 4, 1.85, 1, 100, save=SAVE, loc_rwd=2, loc_feat=4, zoom_rwd=1.75, zoom_feat=1.7) 

In [ ]:
seaquest_metrics4 = figure_factory(log_dir, "Seaquest", 4, 1.3, 1.5, 100, save=SAVE, loc_rwd=2, loc_feat=1, zoom_rwd=2.1, zoom_feat=1.2) 

In [ ]:
# seeds set

pong_metrics0 = figure_factory(log_dir, "Pong", 0, 3.85, .75, 100, save=SAVE, loc_rwd=4, loc_feat=1)

In [ ]:
#not saved
breakout_metrics0 = figure_factory(log_dir, "Breakout", 0, 2.4, .5, 100, save=SAVE, loc_rwd=2, loc_feat=4, zoom_rwd=1.5, zoom_feat=2.5)

In [ ]:
#not saved
seaquest_metrics0 = figure_factory(log_dir, "Seaquest", 0, 1.4, .4, 100, save=SAVE, loc_rwd=2, loc_feat=4, zoom_rwd=1.65, zoom_feat=2.5) 

In [20]:
df0 = pd.DataFrame([pong_metrics0, breakout_metrics0, seaquest_metrics0])
df4 = pd.DataFrame([pong_metrics4, breakout_metrics4, seaquest_metrics4])
df=pd.concat([df0,df4])

In [21]:
df

Baseline  ICM, single attention  ICM, double attention      AttA2C  \
0  96.138059             100.000000              96.592801   94.411685   
1  82.247977              89.171067              83.069633  100.000000   
2  96.045262              89.432758              87.058865   65.331944   
0  92.438752             100.000000              91.454840   92.014815   
1  78.797046              85.189829              81.772541  100.000000   
2  89.098096              92.043366              83.936876   66.426037   

          RCM  
0   99.951489  
1   81.334197  
2  100.000000  
0   96.293855  
1   84.179994  
2  100.000000

In [22]:
df.to_numpy().mean(axis=0), df.to_numpy().std(axis=0), np.median(df.to_numpy(),axis=0)

(array([89.12753187, 92.63950328, 87.31425922, 86.36408027, 93.62658931]),
 array([ 6.60826177,  5.57554363,  5.21911844, 14.7673495 ,  7.83900973]),
 array([90.76842391, 90.73806195, 85.49787035, 93.21325007, 98.12267201]))